// bear stocks
var bearStocks = [
    "FCEL",
    "PCG",
    "MUR",
    "MOS",
    "MRO",
    "FLR",
    "RIG",
    "CCL",
    "CGC",
    "PFE",
    "MA",
    "EOD",
    "CAN",
    "AHT",
    "FARM",
    "IBM",
    "JCP",
    "MITT",
    "REPH",
    "TLRY",
];

// wallstreetbet stocks from Dec 2019 https://www.reddit.com/r/wallstreetbets/comments/e9xjut/top_15_mentioned_stocks_today/
var oldwsbstocks = [
    "SPY",
    "LULU",
    "AMD",
    "COST",
    "FB",
    "PTON",
    "CASH",
    "AAPL",
    "GOLD",
    "ROKU",
    "TSLA",
    "AMZN",
    "NFLX",
    "DIS",
];

// https://www.reddit.com/r/stocks/comments/g4a598/created_a_list_of_under_valued_stocks_for_you_guys/
// shit performance
var sixmontholdundervalued = [
    "COF",
    "ADS",
    "AAP",
    "NEM",
    "EMN",
    "MYL",
    "AGN",
    "SIVB",
    "ACN",
    "EW",
    "DXC",
    "PPG",
    "SCHW",
    "BLK",
    "LLY",
    "JPM",
    "ETFC",
    "HON",
    "CCI",
    "MGM",
];

var biggest20202stocks = [
    "TSLA",
    "ZM",
    "SE",
    "NIO",
    "CRWD",
    "MRNA",
    "PTON",
    "QS",
    "BILI",
    "NET",
    "FTCH",
    "DKNG",
    "RUN",
    "FSLY",
    "DNLI",
    "NVAX",    
];


// wallstreetbet stocks from Dec 2020 https://stocks.comment.ai/trending.html
var dec2020wsbstocks = [
    "PLTR",
    "BABA",
    "GME",
    "TSLA",
    "NIO",
    "AMD",
    "PSTH",
    "AI",
    "ICLN",
    "CFO",
    "AAPL",
    "CRSR",
    "AMZN",
    "MSFT",
    "BFT",
    "GM",
    "SNOW",
    "THCB",
    "TV"
]

var sydStocks = [
    "DVAX",
    "APHA",
    "PLTR",
    "PLUG",
    "BABA",
    // "TSLA",
    "NIO",
    "ACB",
    "GME",
    "AI",
    "CRSR",

    "SPCE",
    "TLRY",
    "FCEL",
    "LAZR",
    "CIIC",
    "SOL",
    "QS",
    "JMIA",
    "XPEV"
]
// https://www.swaggystocks.com/dashboard/wallstreetbets/ticker-sentiment
var stocks = allStocks = [
    "JMIA",
    "BLNK",
    "PYPL",
    "FCEL",
    "GS",
    "STAR",
    "IWM",
    "MAS",
    "LI",
    "SBE",
    "ELF",
    "UBER",
    "SBUX",
    "MP",
    "CPA",
    "PDD",
    "ARKW",
    "ECON",
    "RIG",
    "KO",
    "TQQQ",
    "JNJ",
    "FDX",
    "COST",
    "SPY",
    "BABA",
    "TSLA",
    "PLTR",
    "GME",
    "AAPL",
    "AMZN",
    "CAN",
    "NIO",
    "WISH",
    "ARKG",
    "AMD",
    "ICLN",
    "MOD",
    "SNOW",
    "FB",
    "ARKK",
    "PSTH",
    "GLD",
    "BA",
    "NKLA",
    "MSFT",
    "DIS",
    "CRSR",
    "MT",
    "RKT",
    "ARKF",
    "QQQ",
    "QS",
    "AMC",
    "FUBO",
    "PRPL",
    "MRNA",
    "DM",
    "DKNG",
    "PLUG",
    "HOG",
    "NVDA",
    "IPO",
    "IPOC",
    "DEF",
    "MARA",
    "JD",
    "TDOC",
    "RIOT",
    "F",
    "SOLO",
    "MVIS",
    "BOOM",
    "TY",
    "CRM",
    "SQ",
    "PFE",
    "HERO",
    "SHOP",
    "GM",
    "GAL",
    "INTC",
    "IRS",
    "UVXY",
    "CELH",
    "MGNI",
    "SPOT",
    "EAR",
    "ZM",
    "PTON",
    "SPCE",
    "MCD",
    "RDFN",
    "EGO",
    "FSLY",
    "DASH",
    "UPS",
    "ARKQ",
    "GE",
    "NFLX",
    
];

// past stocks: sydStocks
// future stocks: dec2020wsbstocks
stocks = sydStocks;
// stocks = biggest20202stocks;
// stocks = allStocks;
// stocks = bearStocks;
// stocks = oldwsbstocks;

// stocks = dec2020wsbstocks;
// stocks = ["TLRY"];
var keys = require("./.keys");
module.exports = {   
    strategy: "test",
    strategy: "holdall",
    comparisons: ["h3ka", "rsi", "sma", "ema", "bollinger", "trendwatcher", "holdall"],
    comparisons: ["h3ka"],
    alphavantagekey: keys.alphavantage.key,
    alpaca: keys.alpaca,
    stocks: stocks,
    // stocks: ["ZM"],
    startingCapital: 10000 / stocks.length,
    baseAlgoProfit: 1361834748,
    verbose: (stocks.length == 1) ? true : false,
    timeWindow: {
        start: "2020-10-01",
        end: "2020-12-25"
    }
}